spring.application.name=${SPRING_APP_NAME:demo}
#spring.security.user.name=${SECURITY_USERNAME:niru}
#spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}




logging.pattern.console=${LOGPATTERN_CONSOLE:%clr(%d{HH:mm:ss.SSS}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{15}){yellow} - %msg%n}
#server.address=0.0.0.0 //to access over the whole network
server.port=8080